[server]
headless = false
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1a202c"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false